杂项

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -36,6 +36,13 @@ jobs:
           sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
       - name: Install frontend dependencies
         run: pnpm install --no-frozen-lockfile
+      - name: Verify Tag
+        run: |
+          if [ -z "${{ github.ref_name }}" ]; then
+            echo "::error::未检测到有效标签"
+            exit 1
+          fi
+          echo "使用标签: ${{ github.ref_name }}"
       - name: Build the app
         id: build
         uses: tauri-apps/tauri-action@v0
